// Builds the prebuilt native library for every supported target into
// binary/, and regenerates the wasm module embedded for the web. Run it
// before `dart pub publish`:
//
//   dart run tool/build_binaries.dart
//
// Needs the zig in build.zig.zon's minimum_zig_version. The iOS targets also
// need macOS with Xcode.
import 'dart:convert';
import 'dart:io';

import 'package:serverpod_argon2/src/native_target.dart';

Future<void> main() async {
  final packageRoot = File.fromUri(Platform.script).parent.parent.uri;
  final binary = Directory.fromUri(packageRoot.resolve('binary/'));
  final scratch = await Directory.systemTemp.createTemp('serverpod_argon2_');

  try {
    if (binary.existsSync()) await binary.delete(recursive: true);

    for (final target in NativeTarget.all) {
      stdout.writeln('Building ${target.directory} (${target.zigTriple})');
      final built = await target.build(
        packageRoot: packageRoot,
        outputDirectory: scratch.uri,
      );
      final destination = File.fromUri(
        binary.uri.resolve('${target.directory}/${target.libraryName}'),
      );
      await destination.parent.create(recursive: true);
      await built.copy(destination.path);
    }

    stdout.writeln('Building wasm32-freestanding');
    final wasmPrefix = scratch.uri.resolve('zig-out/wasm/');
    await zigBuild(
      packageRoot: packageRoot,
      zigTriple: 'wasm32-freestanding',
      prefix: wasmPrefix,
    );
    final wasm = await File.fromUri(
      wasmPrefix.resolve('bin/serverpod_argon2.wasm'),
    ).readAsBytes();
    await File.fromUri(
      packageRoot.resolve('lib/src/module/argon2_wasm.g.dart'),
    ).writeAsString(_wasmSource(wasm));
  } finally {
    await scratch.delete(recursive: true);
  }

  stdout.writeln('Done. Prebuilt libraries are in ${binary.path}');
}

String _wasmSource(List<int> wasm) {
  final encoded = base64.encode(wasm);
  final lines = [
    for (var i = 0; i < encoded.length; i += 76)
      "    '${encoded.substring(i, (i + 76).clamp(0, encoded.length))}'",
  ];
  return '''
// GENERATED by tool/build_binaries.dart from src/argon2.zig. Do not edit.

/// The wasm build of src/argon2.zig, base64 encoded so the web build needs no
/// separately served asset.
const argon2WasmBase64 =
${lines.join('\n')};
''';
}
